p8105\_hw1\_kw2873
================
Keyi Wang
9/13/2019

I’m an R Markdown document\!

# problem 1: datafram

``` r
  s = rnorm(8)
  v_logi = s > 0
  v_ch = c("A", "B", "C", "D","E", "F", "G", "H")
  v_fa = c("AB", "B", "O", "B","B", "O", "AB", "B")
  
library(tidyverse)
```

    ## ── Attaching packages ────────────────── tidyverse 1.2.1 ──

    ## ✔ ggplot2 3.2.1     ✔ purrr   0.3.2
    ## ✔ tibble  2.1.3     ✔ dplyr   0.8.3
    ## ✔ tidyr   0.8.3     ✔ stringr 1.4.0
    ## ✔ readr   1.3.1     ✔ forcats 0.4.0

    ## ── Conflicts ───────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()

``` r
example_df = tibble(
  samp = s,
  vec_logical = v_logi,
  vec_char = v_ch,
  vec_factor = v_fa
  )
### out put of the example_data fram
example_df
```

    ## # A tibble: 8 x 4
    ##     samp vec_logical vec_char vec_factor
    ##    <dbl> <lgl>       <chr>    <chr>     
    ## 1  0.527 TRUE        A        AB        
    ## 2  1.66  TRUE        B        B         
    ## 3 -0.915 FALSE       C        O         
    ## 4 -1.44  FALSE       D        B         
    ## 5  0.870 TRUE        E        B         
    ## 6  0.268 TRUE        F        O         
    ## 7 -2.06  FALSE       G        AB        
    ## 8  1.45  TRUE        H        B

``` r
### take the mean of each variables
mean(s)
```

    ## [1] 0.04511983

``` r
mean(v_logi)
```

    ## [1] 0.625

``` r
mean(v_ch)
```

    ## Warning in mean.default(v_ch): argument is not numeric or logical:
    ## returning NA

    ## [1] NA

``` r
mean(v_fa)
```

    ## Warning in mean.default(v_fa): argument is not numeric or logical:
    ## returning NA

    ## [1] NA

the mean of my sample is 0.0451198

the mean of my logical vector is 0.625

the mean of my character vector is NA

the mean of my factor vector is NA

**we noticed that both character vector and factor vector do not have
mean**
